apiVersion: v1
kind: Service
metadata:
  name: fastapi-ui
spec:
  selector:
    app: fastapi-ui
  ports:
    - protocol: TCP
      port: 7860
      targetPort: 7860
      nodePort: 30036  # Exposed on localhost:30036
  type: NodePort

